#!/usr/bin/env python3

# Service URL Collector Script
# Tracks all deployed service URLs from Railway for gateway configuration

import subprocess
import json
import re

def collect_service_urls():
    """Collect all service URLs from Railway project"""
    try:
        # Get all services in the project
        result = subprocess.run(
            ["railway", "status", "--json"],
            capture_output=True,
            text=True,
            timeout=60
        )
        
        if result.returncode != 0:
            print("❌ Failed to get Railway status")
            return {}
            
        # Parse the JSON output (if available)
        try:
            status_data = json.loads(result.stdout)
            services = status_data.get('services', [])
        except:
            # Fallback to parsing text output
            services = []
            
        # Alternative: Use railway list and extract URLs manually
        result = subprocess.run(
            ["railway", "domain"],
            capture_output=True,
            text=True,
            timeout=60
        )
        
        print("🔍 Collecting Railway service URLs...")
        
        # Known deployed services based on our deployment
        service_mappings = {
            # Original services
            "team-hub": "https://team-hub-production.up.railway.app",
            "overview": "https://overview-production.up.railway.app", 
            "api-gateway": "https://api-gateway-production-588d.up.railway.app",
            "ai-agents-service": "https://ai-agents-service-production.up.railway.app",
            "smart-campaigns": "https://smart-campaigns-production.up.railway.app",
            "phone-numbers": "https://phone-numbers-production.up.railway.app",
            "analytics-pro": "https://analytics-pro-production.up.railway.app",
            
            # New services (URLs will be generated by Railway)
            "agents": "TBD",
            "ai-brain": "TBD", 
            "agent-store": "TBD",
            "billing-pro": "TBD",
            "call-center": "TBD",
            "voice-lab": "TBD",
            "voice-marketplace": "TBD",
            "flow-builder": "TBD",
            "integrations": "TBD",
            "settings": "TBD",
            "developer-api": "TBD",
            "compliance": "TBD",
            "white-label": "TBD"
        }
        
        return service_mappings
        
    except Exception as e:
        print(f"💥 Error collecting service URLs: {e}")
        return {}

def update_service_config(service_urls):
    """Update service_config.py with new service URLs"""
    try:
        # Read current service config
        with open('service_config.py', 'r') as f:
            content = f.read()
        
        print("📝 Current service configuration detected")
        print("🔧 Service URLs will need to be updated manually after all deployments complete")
        
        # Create a template for the new services
        template = '''
# New services to be added once URLs are available:
NEW_SERVICES = {
'''
        
        for service, url in service_urls.items():
            if url == "TBD":
                template += f'    "{service}": "https://{service}-production.up.railway.app",  # Update when available\\n'
        
        template += "}\n"
        
        print(template)
        
        return True
        
    except Exception as e:
        print(f"💥 Error updating service config: {e}")
        return False

def main():
    print("🚀 Railway Service URL Collector")
    print("="*50)
    
    service_urls = collect_service_urls()
    
    if service_urls:
        print(f"📊 Found {len(service_urls)} services")
        
        print("\\n📋 Current Service Status:")
        for service, url in service_urls.items():
            status = "✅ Deployed" if url != "TBD" else "🚧 Deploying"
            print(f"  {service}: {status}")
            if url != "TBD":
                print(f"    URL: {url}")
        
        update_service_config(service_urls)
    else:
        print("❌ No services found")

if __name__ == "__main__":
    main()
